"""Consolidate over-split Eurotramp products into single products with proper
Medusa options + variants, then delete the redundant member products.

Source of truth: data/curated/eurotramp_merge_groups.json (human-reviewed).
Mechanics verified by the R2 probe:
  add option (POST /options) -> repurpose the canonical's Default variant ->
  add sibling variants (each with Default:'Default' while that option still
  exists) -> delete the leftover Default option -> union images -> delete
  member products. Eurotramp is request-a-quote: every variant gets a single
  {amount:0, currency_code:usd} price (mirrors existing variants).

SKU-collision safety (R5): a member's SKU can't be added as a sibling while the
member product still holds it, so each member is captured + DELETED first, then
its SKU is added as a sibling variant. Full member JSON is captured to the log
before deletion, and a redirects.json breadcrumb is written.

Usage:
    python scripts/merge_eurotramp_variants.py --propose
    python scripts/merge_eurotramp_variants.py --apply --dry-run [--only ID]
    python scripts/merge_eurotramp_variants.py --apply [--only ID] [--limit N]
"""
from __future__ import annotations

import argparse
import datetime
import json
import os
import sys
import time
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))
sys.path.insert(0, str(REPO_ROOT / "scripts"))
REPORTS_DIR = REPO_ROOT / "docs" / "reports"
CURATED = REPO_ROOT / "data" / "curated" / "eurotramp_merge_groups.json"

from shared.medusa_importer import MedusaImporter  # noqa: E402
from reclassify_eurotramp_images import classify  # noqa: E402
from fix_eurotramp_thumbnails import fn_of, photo_rank  # noqa: E402

MEDUSA_URL = os.environ.get(
    "MEDUSA_BACKEND_URL",
    "https://leka-medusa-backend-538978391890.asia-southeast1.run.app",
)
PRICE0 = [{"amount": 0, "currency_code": "usd"}]
PROD_FIELDS = ("id,handle,title,status,thumbnail,images.url,metadata,"
               "options.id,options.title,options.values.value,"
               "variants.id,variants.title,variants.sku,variants.options.value")


def _env_alias() -> None:
    for a, b in (("LEKA_MEDUSA_ADMIN_EMAIL", "MEDUSA_ADMIN_EMAIL"),
                 ("LEKA_MEDUSA_ADMIN_PASSWORD", "MEDUSA_ADMIN_PASSWORD")):
        if not os.environ.get(b) and os.environ.get(a):
            os.environ[b] = os.environ[a]


def get_product(client: MedusaImporter, handle: str) -> dict | None:
    r = client._get("/admin/products", {"handle": handle, "fields": PROD_FIELDS})
    ps = r.get("products", [])
    return ps[0] if ps else None


def union_images(canonical: dict, members: list[dict]) -> tuple[list[str], str]:
    urls = [im["url"] for im in (canonical.get("images") or [])]
    for m in members:
        urls += [im["url"] for im in (m.get("images") or [])]
    # dedup, real-photo-first
    photos = [u for u in urls if classify(fn_of(u)) == "photo"]
    photos = sorted(set(photos), key=lambda u: photo_rank(u), reverse=True)
    rest = [u for u in urls if classify(fn_of(u)) != "photo"]
    merged, seen = [], set()
    for u in photos + rest:
        if u not in seen:
            seen.add(u)
            merged.append(u)
    cur_thumb = canonical.get("thumbnail")
    thumb = cur_thumb if cur_thumb and classify(fn_of(cur_thumb)) == "photo" else (photos[0] if photos else cur_thumb)
    return merged, thumb


def propose(client, data) -> int:
    today = datetime.date.today().isoformat()
    L = [f"# Eurotramp Variant-Merge Proposal — {today}", "",
         "Generated by scripts/merge_eurotramp_variants.py --propose. **No changes made.**",
         "Apply with `--apply` only after approval. Each group keeps the canonical product",
         "(handle preserved/renamed as noted) and folds the members in as variants, then",
         "deletes the member products.", ""]
    ok = True
    total_del = 0
    for g in data["groups"]:
        canon = get_product(client, g["canonical_handle"])
        status = "OK" if canon else "!! CANONICAL MISSING"
        if not canon:
            ok = False
        nvar = 1 + len(g["members"])
        total_del += len(g["members"])
        L.append(f"## {g['id']}  ({g['confidence']}{', multi-axis' if g.get('multi_axis') else ''})")
        L.append("")
        L.append(f"- **Canonical:** `{g['canonical_handle']}`"
                 + (f"  → rename to `{g['canonical_new_handle']}`" if g.get("canonical_new_handle") else "")
                 + f"  [{status}]")
        if canon:
            L.append(f"  - current status: {canon['status']}, "
                     f"images: {len(canon.get('images') or [])}, "
                     f"current options: {[o['title'] for o in (canon.get('options') or [])]}")
        L.append(f"- **Title:** {g['canonical_title']}")
        L.append(f"- **Options:** {json.dumps(g['options'])}")
        L.append(f"- **Result:** {nvar} variants (1 canonical + {len(g['members'])} merged); "
                 f"{len(g['members'])} member products deleted")
        L.append(f"- _{g.get('note','')}_")
        L.append("")
        L.append("| variant | sku | options | source handle | exists |")
        L.append("|---|---|---|---|---|")
        cv = g["canonical_variant"]
        L.append(f"| {cv['title']} | (canonical) | {json.dumps(cv['options'])} | {g['canonical_handle']} | {'yes' if canon else 'NO'} |")
        for m in g["members"]:
            mp = get_product(client, m["handle"])
            if not mp:
                ok = False
            L.append(f"| {m['title']} | {m['sku']} | {json.dumps(m['options'])} | {m['handle']} | {'yes' if mp else 'MISSING'} |")
        L.append("")
    L.append("## needs_review (NOT auto-merged)")
    L.append("")
    for r in data["needs_review"]:
        L.append(f"- **{r['id']}** — {r['reason']}")
        for h in r["handles"]:
            L.append(f"    - {h}")
    L.append("")
    L.append(f"**Net effect if all groups applied:** {total_del} member products deleted "
             f"(187 → {187 - total_del}).")
    out = REPORTS_DIR / f"eurotramp-merge-proposal-{today}.md"
    out.write_text("\n".join(L), encoding="utf-8")
    print("\n".join(L[:4]))
    print(f"\nGroups: {len(data['groups'])}, members to delete: {total_del}, "
          f"needs_review: {len(data['needs_review'])}")
    print(f"All canonical/member handles resolve: {ok}")
    print(f"Proposal written: {out}")
    return 0 if ok else 1


def apply_group(client, g, dry, log) -> dict:
    gid = g["id"]
    canon = get_product(client, g["canonical_handle"])
    if not canon:
        return {"id": gid, "status": "skip_no_canonical"}
    pid = canon["id"]
    # Idempotency: already merged if the target option titles are present.
    cur_opt_titles = {o["title"] for o in (canon.get("options") or [])}
    if set(g["options"]).issubset(cur_opt_titles):
        return {"id": gid, "status": "already_merged"}

    members = []
    for m in g["members"]:
        mp = get_product(client, m["handle"])
        if not mp:
            return {"id": gid, "status": "abort_member_missing", "missing": m["handle"]}
        members.append((m, mp))

    # Optional: the canonical's repurposed Default variant needs a SKU currently
    # held by another product (free_sku_from) — that product is folded in too.
    cv = g["canonical_variant"]
    free_from = None
    if cv.get("free_sku_from"):
        free_from = get_product(client, cv["free_sku_from"])
        if not free_from:
            return {"id": gid, "status": "abort_free_sku_missing", "missing": cv["free_sku_from"]}

    img_pool = [mp for _, mp in members] + ([free_from] if free_from else [])
    deletes = [m["handle"] for m, _ in members] + ([cv["free_sku_from"]] if free_from else [])
    rec = {"id": gid, "canonical": g["canonical_handle"], "members": [m["handle"] for m, _ in members],
           "actions": []}
    if dry:
        merged_imgs, thumb = union_images(canon, img_pool)
        rec["status"] = "dry_run"
        rec["plan"] = {
            "rename_to": g.get("canonical_new_handle"),
            "add_options": g["options"],
            "canonical_variant": cv,
            "add_variants": [{"title": m["title"], "sku": m["sku"], "options": m["options"]} for m, _ in members],
            "union_images": len(merged_imgs), "thumbnail": fn_of(thumb),
            "delete_products": deletes,
        }
        return rec

    def post(path, body):
        client._post(path, body)

    # 1) rename / retitle canonical
    upd = {}
    if g.get("canonical_new_handle") and canon["handle"] != g["canonical_new_handle"]:
        upd["handle"] = g["canonical_new_handle"]
    if canon.get("title") != g["canonical_title"]:
        upd["title"] = g["canonical_title"]
    if upd:
        post(f"/admin/products/{pid}", upd); rec["actions"].append(f"rename/title {upd}")

    # 2) add options
    for title, values in g["options"].items():
        post(f"/admin/products/{pid}/options", {"title": title, "values": values})
    rec["actions"].append(f"added options {list(g['options'])}")

    canon_target = g.get("canonical_new_handle") or g["canonical_handle"]
    redirects = {}

    # 3) union images BEFORE deleting any member (we already hold their image data)
    merged_imgs, thumb = union_images(canon, img_pool)
    post(f"/admin/products/{pid}", {"images": [{"url": u} for u in merged_imgs], "thumbnail": thumb})
    rec["actions"].append(f"unioned images -> {len(merged_imgs)}")

    # 4) if the canonical variant needs a SKU held by another product, delete
    #    that product first to free the SKU.
    if free_from:
        log.setdefault("deleted_products", []).append(free_from)
        client.session.delete(f"{client.base_url}/admin/products/{free_from['id']}").raise_for_status()
        redirects[cv["free_sku_from"]] = canon_target
        rec["actions"].append(f"deleted free_sku_from {cv['free_sku_from']}")
        time.sleep(0.15)

    # 5) repurpose the canonical Default variant (optionally taking a freed SKU)
    default_vid = canon["variants"][0]["id"]
    repurpose = {"title": cv["title"], "options": {"Default": "Default", **cv["options"]}}
    if cv.get("sku"):
        repurpose["sku"] = cv["sku"]
    post(f"/admin/products/{pid}/variants/{default_vid}", repurpose)
    rec["actions"].append(f"repurposed default variant -> {cv['title']}")

    # 6) per member: capture -> delete product (frees SKU) -> add sibling variant
    for m, mp in members:
        log.setdefault("deleted_products", []).append(mp)  # full snapshot for rollback
        client.session.delete(f"{client.base_url}/admin/products/{mp['id']}").raise_for_status()
        redirects[m["handle"]] = canon_target
        time.sleep(0.15)
        post(f"/admin/products/{pid}/variants",
             {"title": m["title"], "sku": m["sku"], "manage_inventory": False,
              "prices": PRICE0, "options": {"Default": "Default", **m["options"]}})
        time.sleep(0.15)
    rec["actions"].append(f"deleted {len(members)} members + added sibling variants")
    rec["redirects"] = redirects

    # 6) delete the leftover Default option
    fresh = get_product(client, g.get("canonical_new_handle") or g["canonical_handle"])
    dft = [o["id"] for o in (fresh.get("options") or []) if o["title"] == "Default"]
    if dft:
        client.session.delete(f"{client.base_url}/admin/products/{pid}/options/{dft[0]}").raise_for_status()
        rec["actions"].append("deleted Default option")

    # 7) breadcrumb metadata on canonical
    now = datetime.datetime.now(datetime.UTC).isoformat()
    meta = dict(canon.get("metadata") or {})
    meta["merged_handles"] = [m["handle"] for m, _ in members] + ([cv["free_sku_from"]] if free_from else [])
    meta["merged_at"] = now
    post(f"/admin/products/{pid}", {"metadata": meta})
    rec["status"] = "merged"
    return rec


def main() -> int:
    ap = argparse.ArgumentParser()
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--propose", action="store_true")
    g.add_argument("--apply", action="store_true")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--only", default="", help="Apply only this group id")
    ap.add_argument("--limit", type=int, default=0)
    args = ap.parse_args()

    data = json.loads(CURATED.read_text(encoding="utf-8"))
    _env_alias()
    client = MedusaImporter(base_url=MEDUSA_URL)
    if not client.api_key:
        print("ERROR: no Medusa admin auth.", file=sys.stderr)
        return 2

    if args.propose:
        return propose(client, data)

    groups = data["groups"]
    if args.only:
        groups = [x for x in groups if x["id"] == args.only]
    if args.limit:
        groups = groups[: args.limit]

    today = datetime.date.today().isoformat()
    log = {"generated_at": datetime.datetime.now(datetime.UTC).isoformat(),
           "mode": "dry-run" if args.dry_run else "apply", "groups": []}
    redirects_all = {}
    for grp in groups:
        print(f"\n=== {grp['id']} ===")
        rec = apply_group(client, grp, args.dry_run, log)
        log["groups"].append(rec)
        print(f"  {rec['status']}")
        for a in rec.get("actions", []):
            print(f"   - {a}")
        redirects_all.update(rec.get("redirects", {}))

    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    suffix = "dry" if args.dry_run else "apply"
    log_path = REPORTS_DIR / f"eurotramp-merge-log-{today}-{suffix}.json"
    log_path.write_text(json.dumps(log, indent=2, ensure_ascii=False), encoding="utf-8")
    if redirects_all and not args.dry_run:
        (REPORTS_DIR / f"eurotramp-merge-redirects-{today}.json").write_text(
            json.dumps(redirects_all, indent=2), encoding="utf-8")
    print(f"\nLog: {log_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
