"""Mark Weplay product docs whose `name` + `description` were generated by
the upstream Anthropic-Vision scrape pipeline (NOT by any of this
session's authoritative sources) so future enrichment passes know the
content lineage.

Background — why these docs look "uncovered"
--------------------------------------------
v2.13.0 introduced source-priority writeback: each enrichment script only
writes when `source_url_en` (live), `source_url_cached` (GCS HTML),
`source_url_flipbook` (2025 flipbook OCR), `source_url_local` (text PDF),
or `source_url_pdf_ocr` (Vision OCR of image PDF) is unset. This guards
against clobber when re-running scripts.

Side effect: the ~103 drafts that the upstream pipeline created BEFORE
this session — and that this session's scrapes didn't re-cover — show
up as "uncovered" in coverage reports. But their `name` + `description`
fields are already populated (with Anthropic-Vision-inferred content,
documented in their `notes` field as "Product identified as ... based
on visual appearance").

What this script writes
-----------------------
For each product where:
  - status == "draft_no_images"
  - has a real-SKU `item_code`
  - has non-empty `name` (so there IS content worth claiming)
  - lacks all 5 `source_url_*` markers

Set:
  source_ai_inferred = True
  source_ai_pipeline = "anthropic_vision_v1"  (provenance label)
  source_ai_sha     = <existing source_sha>   (page hash for re-tracing)

Doesn't change `status` — keeps as draft (data quality is too uncertain
to promote sight-unseen). Doesn't change `name`/`description`. Just
stamps lineage so future passes can decide what to do.

Usage:
    py scripts/stamp_weplay_ai_inferred.py --dry-run
    py scripts/stamp_weplay_ai_inferred.py --apply
"""
from __future__ import annotations

import argparse
import logging
import os
import re
import sys
from collections import Counter

from google.cloud import firestore

_FALLBACK_ADC = (
    r"C:\Users\Eukrit\AppData\Roaming\gcloud\legacy_credentials"
    r"\codex-chatgpt@ai-agents-go.iam.gserviceaccount.com\adc.json"
)
if "GOOGLE_APPLICATION_CREDENTIALS" not in os.environ or not os.path.exists(
    os.environ.get("GOOGLE_APPLICATION_CREDENTIALS", "")
):
    if os.path.exists(_FALLBACK_ADC):
        os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = _FALLBACK_ADC
os.environ.setdefault("GOOGLE_CLOUD_PROJECT", "ai-agents-go")

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s: %(message)s")
log = logging.getLogger("stamp_weplay_ai_inferred")

PROJECT = "ai-agents-go"
DB = "vendors"
SLUG = "weplay"
SKU_TOKEN_RE = re.compile(r"([A-Z]{2}[0-9]{4,})")
SOURCE_KEYS = ("source_url_en", "source_url_cached", "source_url_flipbook",
               "source_url_local", "source_url_pdf_ocr", "source_ai_inferred")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    mode = ap.add_mutually_exclusive_group(required=True)
    mode.add_argument("--apply", action="store_true")
    mode.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()
    write = bool(args.apply)
    log.info("=== stamp_weplay_ai_inferred mode=%s ===", "WRITE" if write else "DRY-RUN")

    db = firestore.Client(project=PROJECT, database=DB)
    coll = db.collection("vendors").document(SLUG).collection("products")

    counters = {
        "scanned": 0,
        "skipped_not_draft": 0,
        "skipped_no_real_sku": 0,
        "skipped_no_name": 0,
        "skipped_already_sourced": 0,
        "stamped": 0,
    }
    sample_stamps: list[str] = []
    sample_skipped_no_name: list[str] = []
    by_prefix: Counter[str] = Counter()
    batch = db.batch()
    batch_n = 0

    for snap in coll.stream():
        counters["scanned"] += 1
        d = snap.to_dict() or {}
        if d.get("status") != "draft_no_images":
            counters["skipped_not_draft"] += 1
            continue
        sku = (d.get("item_code") or "").upper()
        m = SKU_TOKEN_RE.search(sku)
        if not m:
            counters["skipped_no_real_sku"] += 1
            continue
        if any(d.get(k) for k in SOURCE_KEYS):
            counters["skipped_already_sourced"] += 1
            continue
        name = (d.get("name") or "").strip()
        if not name:
            counters["skipped_no_name"] += 1
            if len(sample_skipped_no_name) < 5:
                sample_skipped_no_name.append(f"{snap.id} sku={sku}")
            continue

        token = m.group(1)
        by_prefix[token[:2]] += 1
        counters["stamped"] += 1
        if len(sample_stamps) < 12:
            sample_stamps.append(f"{snap.id} sku={sku} name={name[:50]!r}")

        payload = {
            "source_ai_inferred": True,
            "source_ai_pipeline": "anthropic_vision_v1",
            "source_ai_sha": d.get("source_sha"),
        }
        if write:
            batch.set(snap.reference, payload, merge=True)
            batch_n += 1
            if batch_n >= 200:
                batch.commit()
                log.info("committed batch (%d)", batch_n)
                batch = db.batch()
                batch_n = 0

    if write and batch_n:
        batch.commit()
        log.info("committed final batch (%d)", batch_n)

    log.info("=== summary ===")
    for k, v in counters.items():
        log.info("  %s: %d", k, v)
    log.info("\nstamped by SKU prefix: %s", dict(by_prefix.most_common()))
    if sample_stamps:
        log.info("\nsample stamps:")
        for s in sample_stamps:
            log.info("  %s", s)
    if sample_skipped_no_name:
        log.info("\nsample skipped (no name):")
        for s in sample_skipped_no_name:
            log.info("  %s", s)
    return 0


if __name__ == "__main__":
    sys.exit(main())
